spring.application.name=solar-shield-subscription

# Database Connection
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/solar_shield_subscriptions}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:si-admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:si-admin}

# Logging Config
logging.level.root=ERROR
logging.level.com.powersolutions.solarshield=INFO

# Security
square.webhook.signature.key=${SQUARE_WEBHOOK_SIGNATURE_KEY:}
square.webhook.notification.url=${SQUARE_WEBHOOK_NOTIFICATION_URL:}