spring.application.name=solar-shield-subscription

# Database Connection
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/solar_shield_subscriptions}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:si-admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:si-admin}

# Logging Config
logging.level.root=ERROR
logging.level.com.powersolutions.solarshield=INFO

# Square Config & Security
square.api.url=${SQUARE_API_URL}
square.access.token=${SQUARE_ACCESS_TOKEN}
square.location.id=${SQUARE_LOCATION_ID}
square.webhook.signature.key=${SQUARE_WEBHOOK_SIGNATURE_KEY}
square.webhook.notification.url=${SQUARE_WEBHOOK_NOTIFICATION}

# Square Subscription Plan Variations
square.subscription.plan.silver=${SQUARE_PLAN_SILVER_ID}
square.subscription.plan.gold=${SQUARE_PLAN_GOLD_ID}
square.subscription.plan.platinum=${SQUARE_PLAN_PLATINUM_ID}
square.subscription.plan.test=${SQUARE_PLAN_TEST_ID}

# Zoho
zoho.api.base.url=${ZOHO_API_BASE_URL:https://www.zohoapis.com/crm/v8/}
zoho.token.base.url=${ZOHO_TOKEN_BASE_URL}
zoho.custom.module.refresh.token=${ZOHO_CUSTOM_MODULE_REFRESH_TOKEN}
zoho.client.id=${ZOHO_CLIENT_ID}
zoho.client.secret=${ZOHO_CLIENT_SECRET}

